---
step-runner-config:
  config-decryptors:
  - implementer: SOPS

  global-defaults:
    organization: ploigos-ref
    service-name: hello

    container-registries:
        registry.redhat.io:
            username: 6340056|tssc-integration-infra
        registry-internal-nexus.apps.tssc.rht-set.com:
            username: sa-ploigos-ref-apps

  generate-metadata:
  - implementer: Npm
  - implementer: Git
  - implementer: SemanticVersion

  tag-source:
    - implementer: Git
      config:
        git-username: sa-ploigos-ref-apps

  unit-test:
    - implementer: NpmTest
      config:
        install-first: True

  package:
  - implementer: NpmPackage

  static-code-analysis:
    - implementer: SonarQube
      config:
        url: https://sonarqube-sonarqube.apps.tssc.rht-set.com/
        username: reference-apps-sa

  push-artifacts:
  - implementer: NpmPushArtifacts
    config:
      npm-registry: https://nexus.apps.tssc.rht-set.com/repository/npm-internal/
      npm-user: sa-ploigos-ref-apps

  create-container-image:
  - implementer: Buildah

  push-container-image:
  - implementer: Skopeo
    config:
      destination-url: registry-internal-nexus.apps.tssc.rht-set.com

  container-image-static-vulnerability-scan:
  - name: OpenSCAP - Vulnerability - DataStream
    implementer: OpenSCAP
    config:
      oscap-input-definitions-uri: https://www.redhat.com/security/data/metrics/ds/v2/RHEL8/rhel-8.ds.xml.bz2
      oscap-tailoring-uri: https://raw.githubusercontent.com/ploigos-reference-apps/ploigos-example-oscap-content/main/xccdf_com.ploigos_profile_default_cve_ploigos_reference_apps-tailoring.xml
      oscap-profile: xccdf_com.ploigos_profile_default_cve_ploigos_reference_quarkus_mvn

  deploy:
  - implementer: ArgoCD
    config:
      argocd-api: argocd-server-argocd.apps.tssc.rht-set.com
      argocd-username: admin
      argocd-skip-tls: True
      deployment-config-helm-chart-path: charts/reference-nodejs-npm-deploy
      deployment-config-helm-chart-values-file-image-tag-yq-path: 'image.tag'
      git-username: sa-ploigos-ref-apps
      git-email: 'napsspo+tssc@redhat.com'
      argocd-sync-timeout-seconds: 130
      force-push-tags: True
    environment-config:
      DEV:
        deployment-config-helm-chart-environment-values-file: values-DEV.yaml
      TEST:
        deployment-config-helm-chart-environment-values-file: values-TEST.yaml
      PROD:
        deployment-config-helm-chart-environment-values-file: values-PROD.yaml

  report:
  - implementer: ResultArtifactsArchive
    config:
      results-archive-destination-url: https://nexus.apps.tssc.rht-set.com/repository/release-engineering-workflow-result-artifacts-archives/
      results-archive-destination-username: sa-ploigos-ref-apps
